### ISSUE TITLE
Needs full documentation

### ISSUE THREAD

**Issue by rocketdyke** [BigNocciolino/CryptoTracker#26]
"The component is available in the hacs store, you only need to search it and after you can configure it from the Devices & Services page in the Configuration page."

well, I've installed it from HACS, and there is nothing in the Devices and Services configuration page. 

with no way to find the GUI, it is impossible to actually configure this to show up.

**Comment by RedNax67** [comment]
It's a bit of a puzzle, but it does mention to go to Devices&Services in config menu. You need to "Add Integration"  -> Cryptostate for every pair.

That said... updates every 12 hours makes the whole thing pointless i my opinion.

**Comment by GigaTech** [comment]
do we still need to install via HACS?

This needs full/better documentation


And what each of these mean?
<img width="460" alt="image" src="https://user-images.githubusercontent.com/3658357/156786186-d05f7645-000e-400c-9b98-414ae680b0f3.png">


How to convert this into a new configuration?
```
sensor:
  - platform: cryptostate
    resources:
      - compare: btc-gbp
        name: crypto-btc-gbp

      - compare: eth-gbp
        name: crypto-eth-gbp
```
