### ISSUE TITLE
Make CryptoTracker compatible with HomeAssistant Long Term Statistics

### ISSUE THREAD

**Issue by itkama** [BigNocciolino/CryptoTracker#4]
Hi,
I tried adding a statistics card for a currency-pair but HA told me there were none available and directed me to this site:
https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics
It looks like there needs to a few small adjustments to make CryptoTracker compatible.
If you need any more info, please let me know :)

**Comment by BigNocciolino** [comment]
Ok, I have to implement this kind of function in the component, give me time to work on it

**Comment by BigNocciolino** [comment]
Ok, for my test it works, you can select the sensors in the drop-down menu, but it takes more data to populate the graph completely.
I leave the trhead open, to get your news on the correct functioning.
These are my settings for now:

**LOVELACE:**
![image](https://user-images.githubusercontent.com/59704096/133279624-ebd3416b-7a85-4e48-b3b3-23915695dc7e.png)

**CONFIG:**

```yaml
sensor:
- platform: cryptostate
  resources:
  - compare: "doge-eur"
    name: "dogecoin"
  - compare: "btc-eur"
    name: "bitcoin"
  - compare: "eth-eur"
    name: "ethereum"
  - compare: "cake-eur"
    name: "cake"
  - compare: "usd-eur"
    name: "dollar"
```
